### ISSUE TITLE
Unable to import component

### ISSUE THREAD

**Issue by ilmaino1984** [sh00t2kill/dolphin-robot#162]
Good morning, this error appears after latest update 12/29/2023.

Setup failed for custom integration 'mydolphin_plus': Unable to import component: Exception importing custom_components.mydolphin_plus
14:30:54 – (ERRORE) setup.py
Unexpected exception importing component custom_components.mydolphin_plus
14:30:54 – (ERRORE) loader.py

Any solution?
Ty regards

**Comment by elad-bar** [comment]
I guess you are not in discord, posted there a message, will share here as well, tl;dr; revert to previous version until next HA release.

Hi all,
I release v1.0.6 to address breaking change of HA v2024.1.0,
Accidentally I didn't add a tag for hacs so that release will take place only after release of HA with the breaking change,
If you have upgraded to v1.0.6 before HA v2024.1.0, integration will not get loaded, to fix it, redownload v1.0.5

**Comment by elad-bar** [comment]
i removed that version will create another one after release of HA

**Comment by elad-bar** [comment]
v1.0.6 removed, created v1.0.8 with minmum HA version 2024.1.0b0,
please report if it works for you and we can close the issue

**Comment by ilmaino1984** [comment]
Hi, thanks for your support. I can't install the 2024.1.0b0 version now. Fortunately i don't need your add-on at this moment. Hope in the new HA version. Thanks a lot, Happy new year.

**Comment by ilmaino1984** [comment]
Good morning. With the new release, it works correctly. Thanks Regards
