### ISSUE TITLE
Service Vacuum not available 

### ISSUE THREAD

**Issue by lbreggi** [sh00t2kill/dolphin-robot#192]
Hi! I’m running this integration version 1.0.12 and HA 2024.5.2. When I try to enable my robot I’m getting a message “service vacuum not found”. Any idea? Thank you! 
![IMG_0083](https://github.com/sh00t2kill/dolphin-robot/assets/25729150/cd0e030b-1a54-47f5-891d-91cdeb7328cc)

**Comment by sh00t2kill** [comment]
How/What were you doing in order to start the vacuum ? Did you flick the switch in the UI ?

The turn_on service was removed some time ago.
From the vacuum docs:

Available services: start, pause, stop, return_to_base, locate, clean_spot, set_fan_speed and send_command.

so, instead call the vacuum.start service, or open up the entity itself and click the start button. Its a little annoying that it doesnt translate turn_on to start any more.

**Comment by Scope666** [comment]
The other thing that works is just pick something from the drop-down menu, like "floor only" ... that immediately turns on the robot and starts the cycle.

**Comment by elad-bar** [comment]
This ui component is provided by HA, it is not related to the error most likely, but to be sure, when opening an issue it will be much clearer if you will provide log (preferably debug level)

Thanks
